import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { PayPalNamespace, loadScript } from "@paypal/paypal-js";
import { useEffect, useRef, useState } from "react";
import { env } from "~/env.mjs";

const PaypalButton = () => {
  const [paypal, setPaypal] = useState<PayPalNamespace | null>();
  const paypalContainerRef = useRef<HTMLDivElement>(null);

  const createOrder  = api.paypal.createOrder.useMutation();

  useEffect(() => {
    loadScript({ 'client-id': env.NEXT_PUBLIC_PAYPAL_CLIENT_ID,  })
      .then((paypal) => {
        setPaypal(paypal);
      })
      .catch(err => {
        console.error('Failed to load PayPal script', err);
        // Handle failure...
      });
  }, []);

  useEffect(() => {
    if (!paypal) {return}
    if (!paypal.Buttons) { return }
    if (!paypalContainerRef.current) { return }
    if (paypalContainerRef.current.hasChildNodes()) { return }

    paypal.Buttons({

      onApprove: function (data, actions) {
        const response = createOrder.mutateAsync({
          amountOfLicenses: 1,
        })

        return new Promise((resolve, reject) => {
          response.then((res) => {
            console.log("res", res)
            // resolve(res);
          }
          ).catch((err) => {
            reject(err)
          })

        })
      },

    }).render(paypalContainerRef.current).catch(err => {
      console.error('Failed to render PayPal buttons', err);
      // Handle failure...
    })
  }, [paypal, paypalContainerRef]);


  return (paypal ? <div ref={paypalContainerRef}></div> : <div>Loading...</div>)
};


const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="w-[500px] bg-white rounded-md p-5" >
            <PaypalButton />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
