import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="w-[500px] flex flex-col gap-5 bg-white rounded-md p-5" >
            <Link className="bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded" href="/licenses">
              Licenses
            </Link>
            <Link className="bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded" href="/checkout">
              Checkout
            </Link>

          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
